export const options = [{ name: "Algeria", link: "https://mrandmrshowe.com/lifestyle-blog/algeria-tourist-visa-application-filipino" },
{ name: "Albania", link: "https://mrandmrshowe.com/lifestyle-blog/albania-tourist-visa-application-filipino" },
{ name: "Angola", link: "https://mrandmrshowe.com/lifestyle-blog/angola-tourist-visa-application-filipino" },
{ name: "Antigua&Barbuda", link: "https://mrandmrshowe.com/lifestyle-blog/antigua-barbuda-evisa-application-filipino" },
{ name: "Argentina", link: "https://mrandmrshowe.com/lifestyle-blog/argentina-visa-application-filipino" },
{ name: "Argentina ETA", link: "https://mrandmrshowe.com/lifestyle-blog/argentina-eta-visa-application-filipino" },
{ name: "Armenia", link: "https://mrandmrshowe.com/lifestyle-blog/armenia-visa-application-filipino" },
{ name: "Australia", link: "https://mrandmrshowe.com/lifestyle-blog/australia-visa-application-filipino" },
{ name: "Austria", link: "https://mrandmrshowe.com/lifestyle-blog/lithuania-austria-visa-application-filipino" },
{ name: "Azerbaijan", link: "https://mrandmrshowe.com/lifestyle-blog/azerbaijan-visa-application-filipino" },
{ name: "Bahamas", link: "https://mrandmrshowe.com/lifestyle-blog/bahamas-tourist-visa-application-filipino" },
{ name: "Bahrain", link: "https://mrandmrshowe.com/lifestyle-blog/bahrain-visa-application-filipino" },
{ name: "Bangladesh", link: "https://mrandmrshowe.com/lifestyle-blog/bangladesh-visa-application-filipino" },
{ name: "Belarus", link: "https://mrandmrshowe.com/lifestyle-blog/belarus-tourist-visa-application-filipino" },
{ name: "Belize", link: "https://mrandmrshowe.com/lifestyle-blog/belize-tourist-visa-application-filipino" },
{ name: "Belgium", link: "https://mrandmrshowe.com/lifestyle-blog/belgium-schengen-visa-philippines-passport" },
{ name: "Bhutan", link: "https://mrandmrshowe.com/lifestyle-blog/bhutan-visa-application-filipino" },
{ name: "Bosnia&Herzegovina", link: "https://mrandmrshowe.com/lifestyle-blog/bosnia-herzegovina-visa-application-filipino" },
{ name: "Canada", link: "https://mrandmrshowe.com/lifestyle-blog/canada-tourist-visa-application-fiipino" },
{ name: "Botswana", link: "https://mrandmrshowe.com/lifestyle-blog/botswana-visa-application-filipino" },
{ name: "Bulgaria", link: "https://mrandmrshowe.com/lifestyle-blog/bulgaria-tourist-visa-philippines-passport" },
{ name: "Chile", link: "https://mrandmrshowe.com/lifestyle-blog/apply-online-chilean-chile-tourist-visa-filipinos" },
{ name: "Croatia", link: "https://mrandmrshowe.com/lifestyle-blog/croatia-visa-application-filipino" },
{ name: "China", link: "https://mrandmrshowe.com/lifestyle-blog/chinese-visa-application-filipino" },
{ name: "Cyprus", link: "https://mrandmrshowe.com/lifestyle-blog/cyprus-visa-application-filipino" },
{ name: "CzechRepublic", link: "https://mrandmrshowe.com/lifestyle-blog/czech-republic-visa-application-filipino" },
{ name: "Denmark", link: "https://mrandmrshowe.com/lifestyle-blog/schengen-visa-denmark-embassy-philippines" },
{ name: "DominicanRepublic", link: "https://mrandmrshowe.com/lifestyle-blog/tourist-visa-dominican-republic-filipino" },
{ name: "Dubai", link: "https://mrandmrshowe.com/lifestyle-blog/dubai-uae-visa-application-filipino" },
{ name: "East Africa Uganda,Rwanda,Kenya", link: "https://mrandmrshowe.com/lifestyle-blog/east-africa-uganda-rwanda-kenya-visa-filipino" },
{ name: "Ecuador", link: "https://mrandmrshowe.com/lifestyle-blog/ecuador-visa-application-filipino" },
{ name: "Egypt", link: "https://mrandmrshowe.com/lifestyle-blog/egypt-tourist-visa-application-filipino" },
{ name: "El Salvador", link: "https://mrandmrshowe.com/lifestyle-blog/el-salvador-visa-application-filipino" },
{ name: "Estonia", link: "https://mrandmrshowe.com/lifestyle-blog/estonia-schengen-visa-application-filipino" },
{ name: "Ethiopia", link: "https://mrandmrshowe.com/lifestyle-blog/ethiopia-visa-application-filipino" },
{ name: "Fiji", link: "https://mrandmrshowe.com/lifestyle-blog/fiji-visa-application-filipino" },
{ name: "Finland", link: "https://mrandmrshowe.com/lifestyle-blog/finland-schengen-visa-application-filipino" },
{ name: "France", link: "https://mrandmrshowe.com/lifestyle-blog/france-schengen-visa-application-filipino" },
{ name: "Gabon", link: "https://mrandmrshowe.com/lifestyle-blog/gabon-visa-application-filipino" },
{ name: "Georgia", link: "https://mrandmrshowe.com/lifestyle-blog/georgia-visa-application-filipino" },
{ name: "Germany", link: "https://mrandmrshowe.com/lifestyle-blog/schengen-visa-germany-application-philippines-passport" },
{ name: "Greece", link: "https://mrandmrshowe.com/lifestyle-blog/greece-schengen-visa-application-filipino" },
{ name: "Grenada", link: "https://mrandmrshowe.com/lifestyle-blog/grenada-tourist-visa-application-filipino" },
{ name: "Guatemala", link: "https://mrandmrshowe.com/lifestyle-blog/guatemala-visa-application-filipino" },
{ name: "Guyana", link: "https://mrandmrshowe.com/lifestyle-blog/guyana-visa-application-filipino" },
{ name: "Haiti", link: "https://mrandmrshowe.com/lifestyle-blog/haiti-visa-application-filipino" },
{ name: "Honduras", link: "https://mrandmrshowe.com/lifestyle-blog/honduras-visa-application-filipino" },
{ name: "Hungary", link: "https://mrandmrshowe.com/lifestyle-blog/hungary-visa-application-filipino" },
{ name: "Iceland", link: "https://mrandmrshowe.com/lifestyle-blog/schengen-visa-iceland-application-philippines-passport" },
{ name: "India", link: "https://mrandmrshowe.com/lifestyle-blog/india-visa-application-filipino" },
{ name: "Indonesia", link: "https://mrandmrshowe.com/lifestyle-blog/indonesia-visa-application-filipino" },
{ name: "Iran", link:"https://mrandmrshowe.com/lifestyle-blog/iran-visa-application-filipino" },
{ name: "Iraq", link: "https://mrandmrshowe.com/lifestyle-blog/iraq-visa-application-filipino" },
{ name: "Ireland", link: "https://mrandmrshowe.com/lifestyle-blog/ireland-visa-application-filipino" },
{ name: "Israel", link: "https://mrandmrshowe.com/lifestyle-blog/israel-visa-application-filipino" },
{ name: "Italy", link: "https://mrandmrshowe.com/lifestyle-blog/italy-schengen-visa-application-filipino" },
{ name: "Jamaica", link: "https://mrandmrshowe.com/lifestyle-blog/jamaica-tourist-visa-application-filipino" },
{ name: "Japan", link: "https://mrandmrshowe.com/lifestyle-blog/japan-visa-application-filipino" },
{ name: "Jordan", link: "https://mrandmrshowe.com/lifestyle-blog/jordan-visa-application-filipino" },
{ name: "Kazakhstan", link: "https://mrandmrshowe.com/lifestyle-blog/kazakhstan-visa-application-filipino" },
{ name: "Kyrgyzstan", link: "https://mrandmrshowe.com/lifestyle-blog/kyrgyzstan-visa-application-filipino" },
{ name: "Kuwait", link: "https://mrandmrshowe.com/lifestyle-blog/tourist-visa-kuwait-application-filipino" },
{ name: "Latvia", link: "https://mrandmrshowe.com/lifestyle-blog/latvia-schengen-visa-philippines-passport" },
{ name: "Lebanon", link: "https://mrandmrshowe.com/lifestyle-blog/lebanon-visa-application-filipino" },
{ name: "Macedonia", link: "https://mrandmrshowe.com/lifestyle-blog/macedonia-visa-application-filipino" },
{ name: "Liechtenstein", link: "https://mrandmrshowe.com/lifestyle-blog/liechtenstein-schengen-visa-philippines-passport" },
{ name: "Luxembourg", link: "https://mrandmrshowe.com/lifestyle-blog/luxembourg-visa-application-filipino" },
{ name: "Madagascar", link: "https://mrandmrshowe.com/lifestyle-blog/madagascar-visa-on-arrival-filipino" },
{ name: "Malta", link: "https://mrandmrshowe.com/lifestyle-blog/malta-schengen-visa-filipino" },
{ name: "Marshall Islands", link: "https://mrandmrshowe.com/lifestyle-blog/marshall-islands-visa-on-arrival-filipino" },
{ name: "Mauritius", link: "https://mrandmrshowe.com/lifestyle-blog/mauritius-visa-on-arrival-philippines-passport" },
{ name: "Moldova", link: "https://mrandmrshowe.com/lifestyle-blog/moldova-visa-application-filipino" },
{ name: "Monaco", link: "https://mrandmrshowe.com/lifestyle-blog/monaco-visa-application-filipino" },
{ name: "Montenegro", link: "https://mrandmrshowe.com/lifestyle-blog/montenegro-tourist-visa-philippines-passport" },
{ name: "Montserrat", link: "https://mrandmrshowe.com/lifestyle-blog/montserrat-visa-application-filipino" },
{ name: "Mexico", link: "https://mrandmrshowe.com/lifestyle-blog/mexico-tourist-visa-application-filipino" },
{ name: "Pakistan", link: "https://mrandmrshowe.com/lifestyle-blog/pakistan-visa-application-filipino" },
{ name: "Palau", link: "https://mrandmrshowe.com/lifestyle-blog/palau-visa-on-arrival-filipino" },
{ name: "Panama", link: "https://mrandmrshowe.com/lifestyle-blog/panama-visa-application-filipino" },
{ name: "Poland", link: "https://mrandmrshowe.com/lifestyle-blog/poland-schengen-visa-application-filipino" },
{ name: "Paraguay", link: "https://mrandmrshowe.com/lifestyle-blog/paraguay-visa-application-filipino" },
{ name: "Portugal", link: "https://mrandmrshowe.com/lifestyle-blog/portugal-schengen-visa-philippines-passport" },
{ name: "Qatar", link: "https://mrandmrshowe.com/lifestyle-blog/qatar-evisa-application-filipino" },
{ name: "Romania", link: "https://mrandmrshowe.com/lifestyle-blog/romania-visa-application-filipino" },
{ name: "Russia", link: "https://mrandmrshowe.com/lifestyle-blog/russia-tourist-visa-application-filipino" },
{ name: "Samoa", link: "https://mrandmrshowe.com/lifestyle-blog/samoa-permit-on-arrival-filipino" },
{ name: "Vatican/San Marino", link: "https://mrandmrshowe.com/lifestyle-blog/vatican-visa-san-marino-visa-application-filipino" },
{ name: "Saudi Arabia", link: "https://mrandmrshowe.com/lifestyle-blog/saudi-arabia-visa-application-filipino" },
{ name: "Schengen", link: "https://mrandmrshowe.com/lifestyle-blog/schengen-visa-application-filipino" },
{ name: "Serbia", link: "https://mrandmrshowe.com/lifestyle-blog/serbia-visa-application-filipino" },
{ name: "Slovakia", link: "https://mrandmrshowe.com/lifestyle-blog/slovakia-visa-application-filipino" },
{ name: "West Africa Visa Guide", link: "https://mrandmrshowe.com/lifestyle-blog/visa-guide-west-africa-filipinos" },
{ name: "Central Africa Visa Application Guide", link: "https://mrandmrshowe.com/lifestyle-blog/visa-application-guide-central-africa-filipinos" },
];

export default options
